// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYDc8eSbCx_tVa1Pm_aInCu17WebM30EQ',
    appId: '1:908731122719:web:d8ec6f13c6aa4b3d8d812a',
    messagingSenderId: '908731122719',
    projectId: 'my-shire-29d68',
    authDomain: 'my-shire-29d68.firebaseapp.com',
    databaseURL: 'https://my-shire-29d68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-shire-29d68.appspot.com',
    measurementId: 'G-5C7FETDMWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxPYeoaYiDqDS5GM1eZoDTLtYzvViI0lg',
    appId: '1:908731122719:android:3d74e9557b8d38f98d812a',
    messagingSenderId: '908731122719',
    projectId: 'my-shire-29d68',
    databaseURL: 'https://my-shire-29d68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-shire-29d68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgQ4rByPptcI-7hWjO8d6WUoKm-LqtNv4',
    appId: '1:908731122719:ios:caf9cdbf1e6c84aa8d812a',
    messagingSenderId: '908731122719',
    projectId: 'my-shire-29d68',
    databaseURL: 'https://my-shire-29d68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-shire-29d68.appspot.com',
    iosBundleId: 'com.shirecommunity.myShire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgQ4rByPptcI-7hWjO8d6WUoKm-LqtNv4',
    appId: '1:908731122719:ios:41b69c2d6d89ae018d812a',
    messagingSenderId: '908731122719',
    projectId: 'my-shire-29d68',
    databaseURL: 'https://my-shire-29d68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-shire-29d68.appspot.com',
    iosBundleId: 'com.shirecommunity.myShire.RunnerTests',
  );
}
