// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACU4Qt7oRrYEe63kKYUAX8hOOVAoTY5Zk',
    appId: '1:856010103802:web:978f84e552fc65e40ae243',
    messagingSenderId: '856010103802',
    projectId: 'ecoalert-5ac12',
    authDomain: 'ecoalert-5ac12.firebaseapp.com',
    storageBucket: 'ecoalert-5ac12.appspot.com',
    measurementId: 'G-DW52XYJ1Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhW_ipenXbgB4Xxjx9YPArk5M2XXeYZ9c',
    appId: '1:856010103802:android:ab219a9b4d1d6a2b0ae243',
    messagingSenderId: '856010103802',
    projectId: 'ecoalert-5ac12',
    storageBucket: 'ecoalert-5ac12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_DXCzFGQGqNpmNIzX1Vjc7JSkuXkFEbk',
    appId: '1:856010103802:ios:efa63a0f6e6e94a60ae243',
    messagingSenderId: '856010103802',
    projectId: 'ecoalert-5ac12',
    storageBucket: 'ecoalert-5ac12.appspot.com',
    iosBundleId: 'com.ecoalert.ecoAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_DXCzFGQGqNpmNIzX1Vjc7JSkuXkFEbk',
    appId: '1:856010103802:ios:efa63a0f6e6e94a60ae243',
    messagingSenderId: '856010103802',
    projectId: 'ecoalert-5ac12',
    storageBucket: 'ecoalert-5ac12.appspot.com',
    iosBundleId: 'com.ecoalert.ecoAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACU4Qt7oRrYEe63kKYUAX8hOOVAoTY5Zk',
    appId: '1:856010103802:web:978f84e552fc65e40ae243',
    messagingSenderId: '856010103802',
    projectId: 'ecoalert-5ac12',
    authDomain: 'ecoalert-5ac12.firebaseapp.com',
    storageBucket: 'ecoalert-5ac12.appspot.com',
    measurementId: 'G-DW52XYJ1Q0',
  );

}